version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    external_links:
      - mongo
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
  mongo-data:
    driver: local
